# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SozDroneGitHub.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtQuickWidgets
from qfi.qfi_ADI import qfi_ADI
from qfi.qfi_ALT import qfi_ALT
from qfi.qfi_HSI import qfi_HSI
from qfi.qfi_TC import qfi_TC
from qfi.qfi_VSI import qfi_VSI
import resimler_rc



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 722)
        MainWindow.setStyleSheet("")
        self.anaWidget = QtWidgets.QWidget(MainWindow)
        self.anaWidget.setStyleSheet("")
        self.anaWidget.setObjectName("anaWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.anaWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ustKisim = QtWidgets.QWidget(self.anaWidget)
        self.ustKisim.setMaximumSize(QtCore.QSize(16777215, 70))
        self.ustKisim.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.ustKisim.setObjectName("ustKisim")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ustKisim)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yerKontrolistasyonBataryaFrame = QtWidgets.QFrame(self.ustKisim)
        self.yerKontrolistasyonBataryaFrame.setStyleSheet("border-radius:6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"color: rgb(211, 215, 207);")
        self.yerKontrolistasyonBataryaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yerKontrolistasyonBataryaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yerKontrolistasyonBataryaFrame.setObjectName("yerKontrolistasyonBataryaFrame")
        self.label_2 = QtWidgets.QLabel(self.yerKontrolistasyonBataryaFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.yerKontrolistasyonBataryaFrame)
        self.lineEdit.setGeometry(QtCore.QRect(230, 10, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.yerKontrolistasyonBataryaFrame)
        self.ustOrtaWidget = QtWidgets.QWidget(self.ustKisim)
        self.ustOrtaWidget.setObjectName("ustOrtaWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ustOrtaWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ustOrtaLabel = QtWidgets.QLabel(self.ustOrtaWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ustOrtaLabel.setFont(font)
        self.ustOrtaLabel.setObjectName("ustOrtaLabel")
        self.verticalLayout_2.addWidget(self.ustOrtaLabel, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.ustOrtaWidget)
        self.ustSagWidget = QtWidgets.QWidget(self.ustKisim)
        self.ustSagWidget.setStyleSheet("")
        self.ustSagWidget.setObjectName("ustSagWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ustSagWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ustSolWidget = QtWidgets.QWidget(self.ustSagWidget)
        self.ustSolWidget.setStyleSheet("border:None")
        self.ustSolWidget.setObjectName("ustSolWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ustSolWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2.addWidget(self.ustSolWidget)
        self.horizontalLayout.addWidget(self.ustSagWidget)
        self.verticalLayout.addWidget(self.ustKisim)
        self.ortaKisim = QtWidgets.QWidget(self.anaWidget)
        self.ortaKisim.setStyleSheet("background-color: rgb(23, 22, 22);\n"
"color: rgb(240, 235, 206);")
        self.ortaKisim.setObjectName("ortaKisim")
        self.gridLayout = QtWidgets.QGridLayout(self.ortaKisim)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.ortaSagStackedWidget = QtWidgets.QStackedWidget(self.ortaKisim)
        self.ortaSagStackedWidget.setMinimumSize(QtCore.QSize(1000, 400))
        self.ortaSagStackedWidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.ortaSagStackedWidget.setStyleSheet("background-color: transparan;")
        self.ortaSagStackedWidget.setObjectName("ortaSagStackedWidget")
        self.arayuzPage = QtWidgets.QWidget()
        self.arayuzPage.setObjectName("arayuzPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.arayuzPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hizContainer = QtWidgets.QFrame(self.arayuzPage)
        self.hizContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.hizContainer.setObjectName("hizContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.hizContainer)
        self.verticalLayout_5.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.hizGraphics = qfi_VSI(self.hizContainer)
        self.hizGraphics.setStyleSheet("")
        self.hizGraphics.setObjectName("hizGraphics")
        self.verticalLayout_5.addWidget(self.hizGraphics)
        self.gridLayout_2.addWidget(self.hizContainer, 0, 1, 1, 1)
        self.irtifaContainer = QtWidgets.QFrame(self.arayuzPage)
        self.irtifaContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.irtifaContainer.setObjectName("irtifaContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.irtifaContainer)
        self.verticalLayout_6.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.irtifaGraphics = qfi_ALT(self.irtifaContainer)
        self.irtifaGraphics.setStyleSheet("")
        self.irtifaGraphics.setObjectName("irtifaGraphics")
        self.verticalLayout_6.addWidget(self.irtifaGraphics)
        self.gridLayout_2.addWidget(self.irtifaContainer, 0, 0, 1, 1)
        self.mapQuickWidget = QtQuickWidgets.QQuickWidget(self.arayuzPage)
        self.mapQuickWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mapQuickWidget.setStyleSheet("border-radius:12px;")
        self.mapQuickWidget.setObjectName("mapQuickWidget")
        self.gridLayout_2.addWidget(self.mapQuickWidget, 1, 1, 1, 1)
        self.dikilmeContainer = QtWidgets.QFrame(self.arayuzPage)
        self.dikilmeContainer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"border-radius:12px;\n"
"")
        self.dikilmeContainer.setObjectName("dikilmeContainer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dikilmeContainer)
        self.verticalLayout_4.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dikilmeGraphics = qfi_ADI(self.dikilmeContainer)
        self.dikilmeGraphics.setObjectName("dikilmeGraphics")
        self.verticalLayout_4.addWidget(self.dikilmeGraphics)
        self.gridLayout_2.addWidget(self.dikilmeContainer, 0, 2, 1, 1)
        self.yatisContainer = QtWidgets.QFrame(self.arayuzPage)
        self.yatisContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.yatisContainer.setObjectName("yatisContainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.yatisContainer)
        self.verticalLayout_7.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.yatisGraphics = qfi_TC(self.yatisContainer)
        self.yatisGraphics.setObjectName("yatisGraphics")
        self.verticalLayout_7.addWidget(self.yatisGraphics)
        self.gridLayout_2.addWidget(self.yatisContainer, 1, 0, 1, 1)
        self.yonelmeContainer = QtWidgets.QFrame(self.arayuzPage)
        self.yonelmeContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.yonelmeContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.yonelmeContainer.setObjectName("yonelmeContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.yonelmeContainer)
        self.verticalLayout_8.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.yonelmeGraphics = qfi_HSI(self.yonelmeContainer)
        self.yonelmeGraphics.setObjectName("yonelmeGraphics")
        self.verticalLayout_8.addWidget(self.yonelmeGraphics)
        self.gridLayout_2.addWidget(self.yonelmeContainer, 1, 2, 1, 1)
        self.ortaSagStackedWidget.addWidget(self.arayuzPage)
        self.ayarlarPage = QtWidgets.QWidget()
        self.ayarlarPage.setObjectName("ayarlarPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ayarlarPage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ayarlarFrameContainer = QtWidgets.QFrame(self.ayarlarPage)
        self.ayarlarFrameContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayarlarFrameContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayarlarFrameContainer.setObjectName("ayarlarFrameContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ayarlarFrameContainer)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ayarlarSolFrame = QtWidgets.QFrame(self.ayarlarFrameContainer)
        self.ayarlarSolFrame.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.ayarlarSolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayarlarSolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayarlarSolFrame.setObjectName("ayarlarSolFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ayarlarSolFrame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ayarlarUstFrame = QtWidgets.QFrame(self.ayarlarSolFrame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ayarlarUstFrame.setFont(font)
        self.ayarlarUstFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayarlarUstFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayarlarUstFrame.setObjectName("ayarlarUstFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.ayarlarUstFrame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ayarlarLabel = QtWidgets.QLabel(self.ayarlarUstFrame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ayarlarLabel.setFont(font)
        self.ayarlarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ayarlarLabel.setObjectName("ayarlarLabel")
        self.verticalLayout_12.addWidget(self.ayarlarLabel)
        self.verticalLayout_11.addWidget(self.ayarlarUstFrame, 0, QtCore.Qt.AlignTop)
        self.ayarlarAltFrame = QtWidgets.QFrame(self.ayarlarSolFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ayarlarAltFrame.sizePolicy().hasHeightForWidth())
        self.ayarlarAltFrame.setSizePolicy(sizePolicy)
        self.ayarlarAltFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayarlarAltFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayarlarAltFrame.setObjectName("ayarlarAltFrame")
        self.comboBox = QtWidgets.QComboBox(self.ayarlarAltFrame)
        self.comboBox.setGeometry(QtCore.QRect(280, 70, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.ayarlarAltFrame)
        self.label.setGeometry(QtCore.QRect(60, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.ayarlarAltFrame)
        self.horizontalLayout_5.addWidget(self.ayarlarSolFrame)
        self.ayarlarSagFrame = QtWidgets.QFrame(self.ayarlarFrameContainer)
        self.ayarlarSagFrame.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.ayarlarSagFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ayarlarSagFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ayarlarSagFrame.setObjectName("ayarlarSagFrame")
        self.horizontalLayout_5.addWidget(self.ayarlarSagFrame)
        self.verticalLayout_10.addWidget(self.ayarlarFrameContainer)
        self.ortaSagStackedWidget.addWidget(self.ayarlarPage)
        self.komutaPage = QtWidgets.QWidget()
        self.komutaPage.setObjectName("komutaPage")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.komutaPage)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.komutaSolFrame = QtWidgets.QFrame(self.komutaPage)
        self.komutaSolFrame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.komutaSolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.komutaSolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.komutaSolFrame.setObjectName("komutaSolFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.komutaSolFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ileriLabel = QtWidgets.QLabel(self.komutaSolFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ileriLabel.sizePolicy().hasHeightForWidth())
        self.ileriLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ileriLabel.setFont(font)
        self.ileriLabel.setObjectName("ileriLabel")
        self.verticalLayout_3.addWidget(self.ileriLabel)
        self.label_3 = QtWidgets.QLabel(self.komutaSolFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.yonLabel = QtWidgets.QLabel(self.komutaSolFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yonLabel.setFont(font)
        self.yonLabel.setObjectName("yonLabel")
        self.verticalLayout_3.addWidget(self.yonLabel)
        self.horizontalLayout_6.addWidget(self.komutaSolFrame)
        self.komutaSagFrame = QtWidgets.QFrame(self.komutaPage)
        self.komutaSagFrame.setStyleSheet("background-color: rgb(85, 87, 83);\n"
"border:none;")
        self.komutaSagFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.komutaSagFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.komutaSagFrame.setObjectName("komutaSagFrame")
        self.guvenliYukLineEdit = QtWidgets.QLineEdit(self.komutaSagFrame)
        self.guvenliYukLineEdit.setGeometry(QtCore.QRect(60, 440, 221, 40))
        self.guvenliYukLineEdit.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.guvenliYukLineEdit.setFont(font)
        self.guvenliYukLineEdit.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"border-radius:12px;\n"
"color: rgb(0, 0, 0);")
        self.guvenliYukLineEdit.setText("")
        self.guvenliYukLineEdit.setObjectName("guvenliYukLineEdit")
        self.yonLineEdit = QtWidgets.QLineEdit(self.komutaSagFrame)
        self.yonLineEdit.setGeometry(QtCore.QRect(240, 260, 221, 40))
        self.yonLineEdit.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yonLineEdit.setFont(font)
        self.yonLineEdit.setWhatsThis("")
        self.yonLineEdit.setAccessibleDescription("")
        self.yonLineEdit.setAutoFillBackground(False)
        self.yonLineEdit.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"border-radius:12px;\n"
"color: rgb(0, 0, 0);")
        self.yonLineEdit.setText("")
        self.yonLineEdit.setPlaceholderText("")
        self.yonLineEdit.setClearButtonEnabled(False)
        self.yonLineEdit.setObjectName("yonLineEdit")
        self.yonSagRadioButon = QtWidgets.QRadioButton(self.komutaSagFrame)
        self.yonSagRadioButon.setGeometry(QtCore.QRect(70, 270, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yonSagRadioButon.setFont(font)
        self.yonSagRadioButon.setObjectName("yonSagRadioButon")
        self.ileriLineEdit = QtWidgets.QLineEdit(self.komutaSagFrame)
        self.ileriLineEdit.setGeometry(QtCore.QRect(50, 80, 221, 40))
        self.ileriLineEdit.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ileriLineEdit.setFont(font)
        self.ileriLineEdit.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"border-radius:12px;\n"
"color: rgb(0, 0, 0);")
        self.ileriLineEdit.setText("")
        self.ileriLineEdit.setObjectName("ileriLineEdit")
        self.yonSolRadioButon = QtWidgets.QRadioButton(self.komutaSagFrame)
        self.yonSolRadioButon.setGeometry(QtCore.QRect(160, 270, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.yonSolRadioButon.setFont(font)
        self.yonSolRadioButon.setObjectName("yonSolRadioButon")
        self.horizontalLayout_6.addWidget(self.komutaSagFrame)
        self.ortaSagStackedWidget.addWidget(self.komutaPage)
        self.kullaniciGirisPage = QtWidgets.QWidget()
        self.kullaniciGirisPage.setObjectName("kullaniciGirisPage")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.kullaniciGirisPage)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.arkaPlanFrame = QtWidgets.QFrame(self.kullaniciGirisPage)
        self.arkaPlanFrame.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"image: url(:/resimler/SOZtransparan.png);")
        self.arkaPlanFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.arkaPlanFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.arkaPlanFrame.setObjectName("arkaPlanFrame")
        self.KullaniciALineEdit = QtWidgets.QLineEdit(self.arkaPlanFrame)
        self.KullaniciALineEdit.setGeometry(QtCore.QRect(670, 320, 174, 26))
        self.KullaniciALineEdit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KullaniciALineEdit.setFont(font)
        self.KullaniciALineEdit.setStyleSheet("background-color: rgb(186, 189, 182);\n"
"border-radius:12px;\n"
"color: rgb(0, 0, 0);")
        self.KullaniciALineEdit.setText("")
        self.KullaniciALineEdit.setObjectName("KullaniciALineEdit")
        self.kullaniciPLabel = QtWidgets.QLabel(self.arkaPlanFrame)
        self.kullaniciPLabel.setGeometry(QtCore.QRect(290, 320, 74, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kullaniciPLabel.setFont(font)
        self.kullaniciPLabel.setStyleSheet("image: None;\n"
"background-color:None;")
        self.kullaniciPLabel.setObjectName("kullaniciPLabel")
        self.KullaniciPLineEdit = QtWidgets.QLineEdit(self.arkaPlanFrame)
        self.KullaniciPLineEdit.setGeometry(QtCore.QRect(670, 170, 174, 26))
        self.KullaniciPLineEdit.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.KullaniciPLineEdit.setFont(font)
        self.KullaniciPLineEdit.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(186, 189, 182);\n"
"border-radius:12px;")
        self.KullaniciPLineEdit.setText("")
        self.KullaniciPLineEdit.setObjectName("KullaniciPLineEdit")
        self.KullaniciALabel = QtWidgets.QLabel(self.arkaPlanFrame)
        self.KullaniciALabel.setGeometry(QtCore.QRect(270, 170, 132, 29))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.KullaniciALabel.setFont(font)
        self.KullaniciALabel.setStyleSheet("background-color:None;\n"
"image:None;")
        self.KullaniciALabel.setObjectName("KullaniciALabel")
        self.horizontalLayout_11.addWidget(self.arkaPlanFrame)
        self.ortaSagStackedWidget.addWidget(self.kullaniciGirisPage)
        self.manuelInisPage = QtWidgets.QWidget()
        self.manuelInisPage.setObjectName("manuelInisPage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.manuelInisPage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.manuelYonerge = QtWidgets.QFrame(self.manuelInisPage)
        self.manuelYonerge.setMaximumSize(QtCore.QSize(550, 16777215))
        self.manuelYonerge.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.manuelYonerge.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manuelYonerge.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manuelYonerge.setObjectName("manuelYonerge")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.manuelYonerge)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.manuelKlavyeYonergeFrame = QtWidgets.QFrame(self.manuelYonerge)
        self.manuelKlavyeYonergeFrame.setStyleSheet("border:none;")
        self.manuelKlavyeYonergeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manuelKlavyeYonergeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manuelKlavyeYonergeFrame.setObjectName("manuelKlavyeYonergeFrame")
        self.Aframe = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.Aframe.setGeometry(QtCore.QRect(60, 170, 41, 31))
        self.Aframe.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.Aframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Aframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Aframe.setObjectName("Aframe")
        self.Alabel = QtWidgets.QLabel(self.Aframe)
        self.Alabel.setGeometry(QtCore.QRect(0, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Alabel.setFont(font)
        self.Alabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color:None;")
        self.Alabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Alabel.setObjectName("Alabel")
        self.Sframe = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.Sframe.setGeometry(QtCore.QRect(110, 170, 41, 31))
        self.Sframe.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.Sframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Sframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Sframe.setObjectName("Sframe")
        self.SLabel = QtWidgets.QLabel(self.Sframe)
        self.SLabel.setGeometry(QtCore.QRect(0, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SLabel.setFont(font)
        self.SLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color:None;")
        self.SLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SLabel.setObjectName("SLabel")
        self.Dframe = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.Dframe.setGeometry(QtCore.QRect(160, 170, 41, 31))
        self.Dframe.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.Dframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Dframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Dframe.setObjectName("Dframe")
        self.DLabel = QtWidgets.QLabel(self.Dframe)
        self.DLabel.setGeometry(QtCore.QRect(0, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.DLabel.setFont(font)
        self.DLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.DLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DLabel.setObjectName("DLabel")
        self.Wframe = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.Wframe.setGeometry(QtCore.QRect(110, 130, 41, 31))
        self.Wframe.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.Wframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Wframe.setObjectName("Wframe")
        self.Wlabel = QtWidgets.QLabel(self.Wframe)
        self.Wlabel.setGeometry(QtCore.QRect(0, 0, 41, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wlabel.sizePolicy().hasHeightForWidth())
        self.Wlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Wlabel.setFont(font)
        self.Wlabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Wlabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color:None;")
        self.Wlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.Wlabel.setObjectName("Wlabel")
        self.SpaceFrame = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.SpaceFrame.setGeometry(QtCore.QRect(290, 170, 151, 31))
        self.SpaceFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.SpaceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SpaceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SpaceFrame.setObjectName("SpaceFrame")
        self.SpaceLabel = QtWidgets.QLabel(self.SpaceFrame)
        self.SpaceLabel.setGeometry(QtCore.QRect(0, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SpaceLabel.setFont(font)
        self.SpaceLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color:None;")
        self.SpaceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.SpaceLabel.setObjectName("SpaceLabel")
        self.ShiftFrame = QtWidgets.QFrame(self.manuelKlavyeYonergeFrame)
        self.ShiftFrame.setGeometry(QtCore.QRect(330, 130, 71, 31))
        self.ShiftFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(186, 189, 182);\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgb(52, 52, 52);\n"
"}")
        self.ShiftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ShiftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ShiftFrame.setObjectName("ShiftFrame")
        self.ShiftLabel = QtWidgets.QLabel(self.ShiftFrame)
        self.ShiftLabel.setGeometry(QtCore.QRect(0, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ShiftLabel.setFont(font)
        self.ShiftLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color:None;")
        self.ShiftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ShiftLabel.setObjectName("ShiftLabel")
        self.DCommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.DCommentLabel.setGeometry(QtCore.QRect(20, 10, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DCommentLabel.setFont(font)
        self.DCommentLabel.setObjectName("DCommentLabel")
        self.ACommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.ACommentLabel.setGeometry(QtCore.QRect(20, 40, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ACommentLabel.setFont(font)
        self.ACommentLabel.setObjectName("ACommentLabel")
        self.WCommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.WCommentLabel.setGeometry(QtCore.QRect(20, 70, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WCommentLabel.setFont(font)
        self.WCommentLabel.setObjectName("WCommentLabel")
        self.SCommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.SCommentLabel.setGeometry(QtCore.QRect(20, 100, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SCommentLabel.setFont(font)
        self.SCommentLabel.setObjectName("SCommentLabel")
        self.ShiftCommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.ShiftCommentLabel.setGeometry(QtCore.QRect(310, 20, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ShiftCommentLabel.setFont(font)
        self.ShiftCommentLabel.setObjectName("ShiftCommentLabel")
        self.SpaceCommentLabel = QtWidgets.QLabel(self.manuelKlavyeYonergeFrame)
        self.SpaceCommentLabel.setGeometry(QtCore.QRect(310, 50, 171, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SpaceCommentLabel.setFont(font)
        self.SpaceCommentLabel.setObjectName("SpaceCommentLabel")
        self.verticalLayout_14.addWidget(self.manuelKlavyeYonergeFrame)
        self.manuelVeriFrame = QtWidgets.QFrame(self.manuelYonerge)
        self.manuelVeriFrame.setEnabled(True)
        self.manuelVeriFrame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.manuelVeriFrame.setStyleSheet("background-color: rgb(136, 138, 133);")
        self.manuelVeriFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.manuelVeriFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.manuelVeriFrame.setObjectName("manuelVeriFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.manuelVeriFrame)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.manuelHizGraphics = qfi_VSI(self.manuelVeriFrame)
        self.manuelHizGraphics.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.manuelHizGraphics.setObjectName("manuelHizGraphics")
        self.horizontalLayout_9.addWidget(self.manuelHizGraphics)
        self.manuelrtifaGraphics = qfi_ALT(self.manuelVeriFrame)
        self.manuelrtifaGraphics.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.manuelrtifaGraphics.setObjectName("manuelrtifaGraphics")
        self.horizontalLayout_9.addWidget(self.manuelrtifaGraphics)
        self.verticalLayout_14.addWidget(self.manuelVeriFrame)
        self.horizontalLayout_8.addWidget(self.manuelYonerge)
        self.manuelQmap = QtQuickWidgets.QQuickWidget(self.manuelInisPage)
        self.manuelQmap.setObjectName("manuelQmap")
        self.horizontalLayout_8.addWidget(self.manuelQmap)
        self.ortaSagStackedWidget.addWidget(self.manuelInisPage)
        self.inisPage = QtWidgets.QWidget()
        self.inisPage.setObjectName("inisPage")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.inisPage)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.inisMenuFrame = QtWidgets.QFrame(self.inisPage)
        self.inisMenuFrame.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.inisMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inisMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inisMenuFrame.setObjectName("inisMenuFrame")
        self.manuelButon = QtWidgets.QPushButton(self.inisMenuFrame)
        self.manuelButon.setGeometry(QtCore.QRect(200, 100, 89, 25))
        self.manuelButon.setObjectName("manuelButon")
        self.landButon = QtWidgets.QPushButton(self.inisMenuFrame)
        self.landButon.setGeometry(QtCore.QRect(200, 270, 89, 25))
        self.landButon.setObjectName("landButon")
        self.rtlButon = QtWidgets.QPushButton(self.inisMenuFrame)
        self.rtlButon.setGeometry(QtCore.QRect(200, 440, 89, 25))
        self.rtlButon.setObjectName("rtlButon")
        self.manuelLabel = QtWidgets.QLabel(self.inisMenuFrame)
        self.manuelLabel.setGeometry(QtCore.QRect(400, 100, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.manuelLabel.setFont(font)
        self.manuelLabel.setObjectName("manuelLabel")
        self.landLabel = QtWidgets.QLabel(self.inisMenuFrame)
        self.landLabel.setGeometry(QtCore.QRect(400, 270, 461, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.landLabel.setFont(font)
        self.landLabel.setObjectName("landLabel")
        self.rtlLabel = QtWidgets.QLabel(self.inisMenuFrame)
        self.rtlLabel.setGeometry(QtCore.QRect(400, 440, 621, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rtlLabel.setFont(font)
        self.rtlLabel.setObjectName("rtlLabel")
        self.horizontalLayout_10.addWidget(self.inisMenuFrame)
        self.ortaSagStackedWidget.addWidget(self.inisPage)
        self.otonomInisPage = QtWidgets.QWidget()
        self.otonomInisPage.setObjectName("otonomInisPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.otonomInisPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.otonomHizContainer = QtWidgets.QFrame(self.otonomInisPage)
        self.otonomHizContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.otonomHizContainer.setObjectName("otonomHizContainer")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.otonomHizContainer)
        self.verticalLayout_16.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.otonomHizGraphics = qfi_VSI(self.otonomHizContainer)
        self.otonomHizGraphics.setStyleSheet("")
        self.otonomHizGraphics.setObjectName("otonomHizGraphics")
        self.verticalLayout_16.addWidget(self.otonomHizGraphics)
        self.gridLayout_4.addWidget(self.otonomHizContainer, 0, 1, 1, 1)
        self.otonomDikilmeContainer = QtWidgets.QFrame(self.otonomInisPage)
        self.otonomDikilmeContainer.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"border-radius:12px;\n"
"")
        self.otonomDikilmeContainer.setObjectName("otonomDikilmeContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.otonomDikilmeContainer)
        self.verticalLayout_15.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.otonomDikilmeGraphics = qfi_ADI(self.otonomDikilmeContainer)
        self.otonomDikilmeGraphics.setObjectName("otonomDikilmeGraphics")
        self.verticalLayout_15.addWidget(self.otonomDikilmeGraphics)
        self.gridLayout_4.addWidget(self.otonomDikilmeContainer, 0, 2, 1, 1)
        self.otonomIrtifaContainer = QtWidgets.QFrame(self.otonomInisPage)
        self.otonomIrtifaContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.otonomIrtifaContainer.setObjectName("otonomIrtifaContainer")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.otonomIrtifaContainer)
        self.verticalLayout_17.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.otonomIrtifaGraphics = qfi_ALT(self.otonomIrtifaContainer)
        self.otonomIrtifaGraphics.setStyleSheet("")
        self.otonomIrtifaGraphics.setObjectName("otonomIrtifaGraphics")
        self.verticalLayout_17.addWidget(self.otonomIrtifaGraphics)
        self.gridLayout_4.addWidget(self.otonomIrtifaContainer, 0, 0, 1, 1)
        self.otonomYonelmeContainer = QtWidgets.QFrame(self.otonomInisPage)
        self.otonomYonelmeContainer.setMinimumSize(QtCore.QSize(0, 0))
        self.otonomYonelmeContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.otonomYonelmeContainer.setObjectName("otonomYonelmeContainer")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.otonomYonelmeContainer)
        self.verticalLayout_19.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.otonomYatisGraphics_2 = qfi_HSI(self.otonomYonelmeContainer)
        self.otonomYatisGraphics_2.setObjectName("otonomYatisGraphics_2")
        self.verticalLayout_19.addWidget(self.otonomYatisGraphics_2)
        self.gridLayout_4.addWidget(self.otonomYonelmeContainer, 1, 2, 1, 1)
        self.otonomYatisContainer = QtWidgets.QFrame(self.otonomInisPage)
        self.otonomYatisContainer.setStyleSheet("border-radius:12px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));")
        self.otonomYatisContainer.setObjectName("otonomYatisContainer")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.otonomYatisContainer)
        self.verticalLayout_18.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.otonomYatisGraphics = qfi_TC(self.otonomYatisContainer)
        self.otonomYatisGraphics.setObjectName("otonomYatisGraphics")
        self.verticalLayout_18.addWidget(self.otonomYatisGraphics)
        self.gridLayout_4.addWidget(self.otonomYatisContainer, 1, 0, 1, 1)
        self.otonomMapQuickWidget = QtQuickWidgets.QQuickWidget(self.otonomInisPage)
        self.otonomMapQuickWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.otonomMapQuickWidget.setStyleSheet("border-radius:12px;")
        self.otonomMapQuickWidget.setObjectName("otonomMapQuickWidget")
        self.gridLayout_4.addWidget(self.otonomMapQuickWidget, 1, 1, 1, 1)
        self.ortaSagStackedWidget.addWidget(self.otonomInisPage)
        self.gridLayout.addWidget(self.ortaSagStackedWidget, 2, 1, 1, 1)
        self.solMenuFrame = QtWidgets.QFrame(self.ortaKisim)
        self.solMenuFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.solMenuFrame.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.solMenuFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.solMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.solMenuFrame.setObjectName("solMenuFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.solMenuFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.durdurButon = QtWidgets.QPushButton(self.solMenuFrame)
        self.durdurButon.setObjectName("durdurButon")
        self.verticalLayout_9.addWidget(self.durdurButon)
        self.baslaButon = QtWidgets.QPushButton(self.solMenuFrame)
        self.baslaButon.setObjectName("baslaButon")
        self.verticalLayout_9.addWidget(self.baslaButon)
        self.GMDButon = QtWidgets.QPushButton(self.solMenuFrame)
        self.GMDButon.setObjectName("GMDButon")
        self.verticalLayout_9.addWidget(self.GMDButon)
        self.pushButton = QtWidgets.QPushButton(self.solMenuFrame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_9.addWidget(self.pushButton)
        self.ayarlarButon = QtWidgets.QPushButton(self.solMenuFrame)
        self.ayarlarButon.setObjectName("ayarlarButon")
        self.verticalLayout_9.addWidget(self.ayarlarButon)
        self.gridLayout.addWidget(self.solMenuFrame, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.ortaKisim)
        self.altKisim = QtWidgets.QWidget(self.anaWidget)
        self.altKisim.setMinimumSize(QtCore.QSize(0, 70))
        self.altKisim.setMaximumSize(QtCore.QSize(16777215, 500))
        self.altKisim.setStyleSheet("background-color: rgb(78, 78, 78);")
        self.altKisim.setObjectName("altKisim")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.altKisim)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.altSolFrame = QtWidgets.QFrame(self.altKisim)
        self.altSolFrame.setStyleSheet("border-radius:6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"color: rgb(211, 215, 207);")
        self.altSolFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altSolFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altSolFrame.setObjectName("altSolFrame")
        self.muhimmatLabel = QtWidgets.QLabel(self.altSolFrame)
        self.muhimmatLabel.setGeometry(QtCore.QRect(70, 16, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.muhimmatLabel.setFont(font)
        self.muhimmatLabel.setStyleSheet("background-color:none;")
        self.muhimmatLabel.setObjectName("muhimmatLabel")
        self.muhimmatLineEdit = QtWidgets.QLineEdit(self.altSolFrame)
        self.muhimmatLineEdit.setGeometry(QtCore.QRect(220, 10, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.muhimmatLineEdit.setFont(font)
        self.muhimmatLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.muhimmatLineEdit.setObjectName("muhimmatLineEdit")
        self.horizontalLayout_3.addWidget(self.altSolFrame)
        self.altOrtaFrame = QtWidgets.QFrame(self.altKisim)
        self.altOrtaFrame.setStyleSheet("border-radius:6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"color: rgb(211, 215, 207);")
        self.altOrtaFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altOrtaFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altOrtaFrame.setObjectName("altOrtaFrame")
        self.BataryaLabel = QtWidgets.QLabel(self.altOrtaFrame)
        self.BataryaLabel.setGeometry(QtCore.QRect(70, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BataryaLabel.setFont(font)
        self.BataryaLabel.setStyleSheet("background-color:none;")
        self.BataryaLabel.setObjectName("BataryaLabel")
        self.bataryaLineEdit = QtWidgets.QLineEdit(self.altOrtaFrame)
        self.bataryaLineEdit.setGeometry(QtCore.QRect(200, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.bataryaLineEdit.setFont(font)
        self.bataryaLineEdit.setStyleSheet("")
        self.bataryaLineEdit.setObjectName("bataryaLineEdit")
        self.horizontalLayout_3.addWidget(self.altOrtaFrame)
        self.altSagFrame = QtWidgets.QFrame(self.altKisim)
        self.altSagFrame.setStyleSheet("border-radius:6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.532801, y1:0.0113636, x2:0.507, y2:0.994, stop:0 rgba(142, 139, 130, 255), stop:1 rgba(52, 52, 52, 255));\n"
"color: rgb(211, 215, 207);")
        self.altSagFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.altSagFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.altSagFrame.setObjectName("altSagFrame")
        self.ModLabel = QtWidgets.QLabel(self.altSagFrame)
        self.ModLabel.setGeometry(QtCore.QRect(90, 10, 67, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ModLabel.setFont(font)
        self.ModLabel.setStyleSheet("background-color:none;")
        self.ModLabel.setObjectName("ModLabel")
        self.ModLineEdit = QtWidgets.QLineEdit(self.altSagFrame)
        self.ModLineEdit.setGeometry(QtCore.QRect(180, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ModLineEdit.setFont(font)
        self.ModLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ModLineEdit.setObjectName("ModLineEdit")
        self.horizontalLayout_3.addWidget(self.altSagFrame)
        self.size_grip = QtWidgets.QFrame(self.altKisim)
        self.size_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.size_grip.setStyleSheet("border:none;")
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_3.addWidget(self.size_grip, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.altKisim)
        MainWindow.setCentralWidget(self.anaWidget)

        self.retranslateUi(MainWindow)
        self.ortaSagStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Station Battery"))
        self.lineEdit.setText(_translate("MainWindow", "N/A"))
        self.ustOrtaLabel.setText(_translate("MainWindow", "SOZ DEFENSE"))
        self.ayarlarLabel.setText(_translate("MainWindow", "SETTINGS"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Dark Mode"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bright Mode"))
        self.label.setText(_translate("MainWindow", "Tema :"))
        self.ileriLabel.setText(_translate("MainWindow", "How Many Meters Do You Want to Go ?"))
        self.label_3.setText(_translate("MainWindow", "Güvenli Yükseklik Kaç Metre?"))
        self.yonLabel.setText(_translate("MainWindow", "How Many Meters Do You Want to Go Left/Right?"))
        self.yonSagRadioButon.setText(_translate("MainWindow", "Right"))
        self.yonSolRadioButon.setText(_translate("MainWindow", "Left"))
        self.kullaniciPLabel.setText(_translate("MainWindow", "Password:"))
        self.KullaniciALabel.setText(_translate("MainWindow", "User name:"))
        self.Alabel.setText(_translate("MainWindow", "A"))
        self.SLabel.setText(_translate("MainWindow", "S"))
        self.DLabel.setText(_translate("MainWindow", "D"))
        self.Wlabel.setText(_translate("MainWindow", "W"))
        self.SpaceLabel.setText(_translate("MainWindow", "SPACE"))
        self.ShiftLabel.setText(_translate("MainWindow", "SHIFT"))
        self.DCommentLabel.setText(_translate("MainWindow", "Press D to go right"))
        self.ACommentLabel.setText(_translate("MainWindow", "Press A to go left"))
        self.WCommentLabel.setText(_translate("MainWindow", "Press W to move forward"))
        self.SCommentLabel.setText(_translate("MainWindow", "Press S to move back"))
        self.ShiftCommentLabel.setText(_translate("MainWindow", "Press SHIFT to go down"))
        self.SpaceCommentLabel.setText(_translate("MainWindow", "Press SPACE to go up"))
        self.manuelButon.setText(_translate("MainWindow", "Manuel"))
        self.landButon.setText(_translate("MainWindow", "Land"))
        self.rtlButon.setText(_translate("MainWindow", "Rtl"))
        self.manuelLabel.setText(_translate("MainWindow", "It allows the user to land the drone on the ground."))
        self.landLabel.setText(_translate("MainWindow", "It allows the drone to land autonomously at its location."))
        self.rtlLabel.setText(_translate("MainWindow", "It is the drone's return home mode and allows it to return to the point where it started and land on the ground."))
        self.durdurButon.setText(_translate("MainWindow", "Stop"))
        self.baslaButon.setText(_translate("MainWindow", "Start"))
        self.GMDButon.setText(_translate("MainWindow", "Gmd"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.ayarlarButon.setText(_translate("MainWindow", "Settings"))
        self.muhimmatLabel.setText(_translate("MainWindow", "AMMO"))
        self.muhimmatLineEdit.setText(_translate("MainWindow", "N/A"))
        self.BataryaLabel.setText(_translate("MainWindow", "BATTERY"))
        self.bataryaLineEdit.setText(_translate("MainWindow", "             N/A"))
        self.ModLabel.setText(_translate("MainWindow", "MODE"))
        self.ModLineEdit.setText(_translate("MainWindow", "N/A"))
